# Default configuration for Multi-Sensor Multi-Object Tracking

# Model parameters
model: 'Brg_rng'  # choices: ['Brg', 'Brg_rng', 'Mixed']
P_D: 0.95
lambda_c: 10
K: 100

# Dynamic parameters
x_dim: 5  # Dimension of state vector x (x, v_x, y, v_y, omega)
v_dim: 3  # Dimension of process noise vector v
T: 1.0    # Sampling time interval
sigma_vel: 5.0
sigma_turn: 0.017453292519943295  # pi/180

# Survival/death parameters
P_S: 0.95
Q_S: 0.05  # 1 - P_S
P_S_clt: 0.9

# Birth model parameters
birth_model:
  num_birth_components: 4
  birth_probability: 0.01  # r in birth model
  birth_positions:
    - [-1500, 0, 250, 0, 0]
    - [-250, 0, 1000, 0, 0]
    - [250, 0, 750, 0, 0]
    - [1000, 0, 1500, 0, 0]
  birth_covariance_diag: [50, 50, 50, 50, "6*(np.pi/180)"]

# Motion model
CT: true

# Scenario parameters
scenario: 'scenario1'

# Dataset options
save_dataset: true
load_dataset: false
dataset_dir: './data'

# Running parameters
verbose: true
enable_logging: true
log_dir: null  # auto-generated if not provided
use_seed: true
seed: 2808
