# Inherits from default.yaml for basic parameters  
# Sensor-specific configurations for bearing only model

# Model configuration
model: 'brg'
num_sensors: 6

# Sensor configurations
sensors:
  positions:
    - [-2000, 0]    # bottom left
    - [2000, 0]     # bottom right
    - [2000, 2000]  # top right
    - [-2000, 2000] # top left
    - [0, 2000]     # top middle
    - [0, 0]        # bottom middle
    
  # Bearing-only sensor parameters
  bearing:
    type: 'brg'
    z_dim: 1
    noise_std: "0.2*np.pi/180"  # D = 0.2*pi/180
    detection_prob: [0.95, 0.95]  # [P_D P_D]
    clutter_rate: [10, 10]  # [lambda_c lambda_c]
    clutter_range: [0, "2*np.pi"]  # [0, 2*pi]
    pdf_c: "1/(2*np.pi)"  # 1/(2*pi)