# Inherits from default.yaml for basic parameters  
# Sensor-specific configurations for bearing-range only model

# Model configuration
model: 'brg_rng'
num_sensors: 4

# Bearing-range sensor configurations
sensors:
  positions: [[-2000, 0], [2000, 0], [2000, 2000], [-2000, 2000]]
  velocities: [[0, 0], [0, 0], [0, -10], [10, 0]]
  bearing_range:
    type: 'brg_rng'
    z_dim: 2
    noise_std: [0.0349, 100]
    detection_prob: [0.98, 0.98]
    clutter_rate: [10, 15]
    pdf_c: 7.957747e-06
  clutter_ranges:
    - [[-1.5708, 1.5708], [0, 4000]]
    - [[1.5708, 4.7124], [0, 4000]]
    - [[1.5708, 4.7124], [0, 4000]]
    - [[-1.5708, 1.5708], [0, 4000]]

# Birth model positions
birth_positions:
  - [-1500, 0, 250, 0, 0]
  - [-250, 0, 1000, 0, 0]
  - [250, 0, 750, 0, 0]
  - [1000, 0, 1500, 0, 0]

birth_covariance_diag: [50, 50, 50, 50, 0.1047]

# Observation parameters specific to bearing-range model
pdf_c: 7.957747154594767e-08  # 1/(pi * 4000)
bearing_D: 0.0349  # 2*pi/180
range_D: 100.0
D: [0.034906585039886595, 100]  # [2*pi/180, range_noise]
