# Inherits from default.yaml for basic parameters  
# Sensor-specific configurations for bearing-range only model

# Model configuration
model: 'brg_rng'
num_sensors: 4

# Bearing-range sensor configurations
sensors:
  positions: [[-2000, 0], [2000, 0], [2000, 2000], [-2000, 2000]]
  velocities: [[0, 0], [0, 0], [0, -10], [10, 0]]
  bearing_range:
    type: 'brg_rng'
    z_dim: 2
    noise_std: ["2*np.pi/180", 10]  # bearing and range standard deviations
    detection_prob: [0.95, 0.95]
    clutter_rate: [10, 10]
    pdf_c: "1/(np.pi * 4000)"  # clutter density
  clutter_ranges:
    - [["-(np.pi/2)", "np.pi/2"], [0, 4000]]  # sensor 1 field of view
    - [["np.pi/2", "3*np.pi/2"], [0, 4000]]   # sensor 2 field of view
    - [["np.pi/2", "3*np.pi/2"], [0, 4000]]   # sensor 3 field of view
    - [["-(np.pi/2)", "np.pi/2"], [0, 4000]]  # sensor 4 field of view

# Birth model positions
birth_positions:
  - [-1500, 0, 250, 0, 0]
  - [-250, 0, 1000, 0, 0]
  - [250, 0, 750, 0, 0]
  - [1000, 0, 1500, 0, 0]

birth_covariance_diag: [50, 50, 50, 50, "6*(np.pi/180)"]  # initial state uncertainty