# Inherits from default.yaml for basic parameters  
# Sensor-specific configurations for mixed bearing and bearing-range model

# Model configuration
model: 'mixed'
num_sensors: 6

# Mixed sensor configurations
sensors:
  sensor_configs:
    # Bearing-only sensors
    - type: 'brg'
      position: [-2000, 0]  # bottom left
      z_dim: 1
      noise_std: "0.2*np.pi/180"  # D = 0.2*pi/180
      detection_prob: [0.95, 0.95]  # [P_D P_D]
      clutter_rate: [10, 10]  # [lambda_c lambda_c]
      clutter_range: [0, "2*np.pi"]  # [0, 2*pi]
      pdf_c: "1/(2*np.pi)"  # 1/(2*pi)
      
    - type: 'brg'
      position: [2000, 0]  # bottom right
      z_dim: 1
      noise_std: "0.2*np.pi/180"  # D = 0.2*pi/180
      detection_prob: [0.95, 0.95]  # [P_D P_D]
      clutter_rate: [10, 10]  # [lambda_c lambda_c]
      clutter_range: [0, "2*np.pi"]  # [0, 2*pi]
      pdf_c: "1/(2*np.pi)"  # 1/(2*pi)
      
    - type: 'brg'
      position: [2000, 2000]  # top right
      velocity: [0, -10]
      z_dim: 1
      noise_std: "0.2*np.pi/180"  # D = 0.2*pi/180
      detection_prob: [0.95, 0.95]  # [P_D P_D]
      clutter_rate: [10, 10]  # [lambda_c lambda_c]
      clutter_range: [0, "2*np.pi"]  # [0, 2*pi]
      pdf_c: "1/(2*np.pi)"  # 1/(2*pi)
      
    - type: 'brg'
      position: [-2000, 2000]  # top left
      velocity: [10, 0]
      z_dim: 1
      noise_std: "0.2*np.pi/180"  # D = 0.2*pi/180
      detection_prob: [0.95, 0.95]  # [P_D P_D]
      clutter_rate: [10, 10]  # [lambda_c lambda_c]
      clutter_range: [0, "2*np.pi"]  # [0, 2*pi]
      pdf_c: "1/(2*np.pi)"  # 1/(2*pi)
      
    # Bearing-range sensors
    - type: 'brg_rng'
      position: [2000, 2000]  # top right
      velocity: [0, -10]
      z_dim: 2
      noise_std: ["2*np.pi/180", 10]  # D = diag([2*pi/180, 10])
      detection_prob: [0.95, 0.95]  # [P_D P_D]
      clutter_rate: [10, 10]  # [lambda_c lambda_c]
      clutter_range: [["np.pi/2", "3*np.pi/2"], [0, 4000]]  # range_c_2 = [pi/2, 3*pi/2; 0, 4000]
      pdf_c: "1/(np.pi * 4000)"  # 1/(pi * 4000)
      
    - type: 'brg_rng'
      position: [-2000, 2000]  # top left
      velocity: [10, 0]
      z_dim: 2
      noise_std: ["2*np.pi/180", 10]  # D = diag([2*pi/180, 10])
      detection_prob: [0.95, 0.95]  # [P_D P_D]
      clutter_rate: [10, 10]  # [lambda_c lambda_c]
      clutter_range: [["-(np.pi/2)", "np.pi/2"], [0, 4000]]  # range_c_1 = [-pi/2, pi/2; 0, 4000]
      pdf_c: "1/(np.pi * 4000)"  # 1/(pi * 4000)

# Birth model positions
birth_positions:
  - [-1500, 0, 250, 0, 0]
  - [-250, 0, 1000, 0, 0]
  - [250, 0, 750, 0, 0]
  - [1000, 0, 1500, 0, 0]

birth_covariance_diag: [50, 50, 50, 50, "6*(np.pi/180)"]  # 6*pi/180
